Numpy:library
10 to 1000 times 


In [1]:
pip install numpy

  Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl (12.5 MB)
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np



In [3]:
print(np.__version__)

2.4.6


In [6]:
name = np.array(["jony","may","julye"])
name

array(['jony', 'may', 'julye'], dtype='<U5')

In [7]:
name.dtype

dtype('<U5')

In [11]:
number1 = np.array([5])
number1


array([5])

In [ ]:
from statistics import mode,mean,median

data = np.array([[78,89,45],[45,90,45]])
data.ndim

2

In [26]:
np.mean(data)

np.float64(65.33333333333333)

In [31]:
values,counts = np.unique(data,return_counts=True)
mode = values[np.argmax(counts)]
print(mode)
print(values)
print(counts)

45
[45 78 89 90]
[3 1 1 1]


In [89]:
# indexing of 1-d
import numpy as np
numdata = np.array([13,56,78,23])
print(numdata[0])
print(np.random.randint(10000))


13
3868


In [ ]:
print(numdata[3])
numdata = np.array([13,56,78,23])
print(numdata[-1])
#first value
print(numdata[0])

np.mean(numdata)
np.median(numdata)


23
23
13


np.float64(39.5)

In [107]:
numdata2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
numdata2.ndim
numdata2[0,0]
numdata2[1,1]
#row1
numdata2[0]
#colum2
numdata2[:,0]

array([10, 40, 70])

In [124]:

numdata2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
numdata2[1:3,1:3]


array([[50, 60],
       [80, 90]])